"$schema"='https://starship.rs/config-schema.json'
add_newline=false


[aws]
symbol=" "

[battery]
charging_symbol=" "
discharging_symbol=" "
empty_symbol=" "
full_symbol=" "
unknown_symbol=" "
[[battery.display]]
threshold=30

[c]
symbol=" "

[character]
error_symbol="[](bold red)"

[cmake]
symbol=" "

[crystal]
symbol=" "

[dart]
symbol=" "

[directory]
read_only=" "

[docker_context]
symbol=" "

[dotnet]
symbol=" "

[elixir]
symbol=" "

[elm]
symbol=" "

[erlang]
symbol=" "

[git_branch]
symbol=" "

[git_commit]
tag_disabled=false
tag_symbol=" "

[golang]
symbol="ﳑ "

[haskell]
symbol=" "

[java]
symbol=" "

[julia]
symbol=" "

[kotlin]
symbol=" "

[lua]
lua_binary="luajit"
symbol=" "

[nix_shell]
symbol=" "

[nodejs]
symbol=" "

[package]
symbol=" "

[perl]
symbol=" "

[php]
symbol=" "

[purescript]
symbol=" "

[python]
symbol=" "

[raku]
symbol=" "

[rlang]
symbol="ﳒ "

[ruby]
symbol=" "

[rust]
symbol=" "

[scala]
symbol=" "

[swift]
symbol="ﯣ "

