"$schema"='https://starship.rs/config-schema.json'
add_newline=false

[aws]
symbol=" "

[azure]
symbol=" "

[battery]
charging_symbol=" "
discharging_symbol=" "
empty_symbol=" "
full_symbol=" "
unknown_symbol=" "
[[battery.display]]
threshold=30

[c]
symbol=" "

[character]
# error_symbol="[](red)"
# success_symbol="[](green)"
error_symbol="[﬌](red)"
success_symbol="[﬌](green)"

[cmake]
symbol=" "

[cobol]
symbol=""

[conda]
symbol="ﭰ"

[container]
symbol=" "

[crystal]
symbol=" "

[daml]
symbol=" "

[dart]
symbol=" "

[directory]
read_only=""

[docker_context]
symbol=" "

[dotnet]
symbol=" "

[elixir]
symbol=" "

[elm]
symbol=" "

[erlang]
symbol=" "

[gcloud]
symbol=" "

[git_branch]
symbol=" "

[git_commit]
tag_disabled=false
tag_symbol=" "

[git_metrics]
disabled=false

[git_status]
ahead="${count}"
behind="${count}"
conflicted=""
deleted=""
diverged=""
modified=""
renamed=""
staged='[\($count\)](green)'
stashed=""
untracked=""
up_to_date=""

[golang]
symbol="ﳑ "

[haskell]
symbol=" "

[helm]
symbol="ﴱ "

[hg_branch]
symbol=" "

[java]
symbol=" "

[julia]
symbol=" "

[kotlin]
symbol=" "

[kubernetes]
symbol="ﴱ "

[lua]
lua_binary="luajit"
symbol=" "

[meson]
symbol=" "

[nim]
symbol=" "

[nix_shell]
symbol=" "

[nodejs]
symbol=" "

[package]
symbol=" "

[perl]
symbol=" "

[php]
symbol=" "

[pulumi]
symbol=" "

[purescript]
symbol=" "

[python]
symbol=" "

[raku]
symbol=" "

[red]
symbol="卑"

[rlang]
symbol="ﳒ "

[ruby]
symbol=" "

[rust]
symbol=" "

[scala]
symbol=" "

[spack]
symbol=" "

[swift]
symbol="ﯣ "

[terraform]
symbol=" "

[vagrant]
symbol=" "

[vlang]
symbol=" "

[zig]
symbol="⚡"

