local g=vim.g
local opt=vim.opt
g.loaded_2html_plugin=1
g.loaded_bugreport=1
g.loaded_compiler=1
g.loaded_ftplugin=1
g.loaded_getscript=1
g.loaded_getscriptPlugin=1
g.loaded_gzip=1
g.loaded_logipat=1
g.loaded_matchit=1
g.loaded_netrw=1
g.loaded_netrwFileHandlers=1
g.loaded_netrwPlugin=1
g.loaded_netrwSettings=1
g.loaded_optwin=1
g.loaded_rplugin=1
g.loaded_rrhelper=1
g.loaded_spellfile_plugin=1
g.loaded_synmenu=1
g.loaded_tar=1
g.loaded_tarPlugin=1
g.loaded_tutor=1
g.loaded_vimball=1
g.loaded_vimballPlugin=1
g.loaded_zip=1
g.loaded_zipPlugin=1
opt.clipboard='unnamedplus' --Copy/paste to system clipboard
opt.colorcolumn='80'
opt.completeopt='menu,menuone,noinsert,noselect'
opt.confirm=true
opt.copyindent=true
opt.expandtab=true
opt.foldmethod='marker'
opt.guicursor='a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor,sm:block-blinkwait175-blinkoff150-blinkon175' --`:help guicursor`
opt.hidden=true --Enable background buffers
opt.ignorecase=true
opt.laststatus=3
opt.linebreak=true --Wrap on word boundary
opt.list=true
opt.listchars:append('eol:')
opt.mouse='a' --Enable mouse support
opt.number=true
opt.relativenumber=true
opt.report=0
opt.rtp:append('/usr/local/opt/fzf')
opt.scrolloff=7
opt.shiftwidth=4
opt.shortmess:append('Ics')
opt.showmatch=true --Highlight matching parenthesis
opt.showmode=true
opt.signcolumn='yes:1'
opt.smartcase=true
opt.smartindent=true --Autoindent new lines
opt.softtabstop=4
opt.splitbelow=true --Horizontal split to the bottom
opt.splitright=true --Vertical split to the right
opt.swapfile=false
opt.tabstop=4
opt.termguicolors=true --Enable 24-bit RGB colors
opt.title=true
opt.updatetime=300
opt.writebackup=false
