vim.opt.clipboard:append('unnamedplus')
vim.opt.completeopt='menu,menuone,noinsert,noselect'
vim.opt.confirm=true
vim.opt.copyindent=true
vim.opt.cursorline=true
vim.opt.expandtab=true
vim.opt.foldmethod='marker'
vim.opt.guicursor='a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor,sm:block-blinkwait175-blinkoff150-blinkon175'
vim.opt.hidden=true
vim.opt.ignorecase=true
vim.opt.laststatus=3
vim.opt.linebreak=true
vim.opt.list=true
vim.opt.listchars:append('eol:')
vim.opt.number=true
vim.opt.relativenumber=true
vim.opt.report=0
vim.opt.scrolloff=7
vim.opt.shiftwidth=4
vim.opt.shortmess:append('Ics')
vim.opt.showmatch=true
vim.opt.showmode=true
vim.opt.signcolumn='yes:1'
vim.opt.smartcase=true
vim.opt.smartindent=true
vim.opt.softtabstop=4
vim.opt.splitbelow=true
vim.opt.splitright=true
vim.opt.swapfile=false
vim.opt.tabstop=4
vim.opt.termguicolors=true
vim.opt.title=true
vim.opt.updatetime=300
vim.opt.writebackup=false
